cloud.aws.stack.auto=false
cloud.aws.region.auto=false
cloud.aws.region.static=ap-northeast-2
cloud.aws.credentials.access-key=AKIAVZDWQDYWILH2M4CC
cloud.aws.credentials.secret-key=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
logging.level.com.amazonaws.util.EC2MetadataUtils=error


cloud.aws.s3.bucket=myweb-fileupload-bucket
cloud.aws.s3.bucket.temp=item/temp/
cloud.aws.s3.bucket.upload=item/upload/





















