cloud.aws.stack.auto=false
cloud.aws.region.auto=false
cloud.aws.region.static=ap-northeast-2
cloud.aws.credentials.access-key=AKIAVZDWQDYWIJD4LBE7
cloud.aws.credentials.secret-key=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
logging.level.com.amazonaws.util.EC2MetadataUtils=error


cloud.aws.s3.bucket=mycloud-shop-bucket
cloud.aws.s3.bucket.temp=item/temp/
cloud.aws.s3.bucket.upload=item/upload/





















